name = "CaratheodoryFejerApprox"
uuid = "591793e0-8db6-4f40-aac6-a66fe5f65964"
authors = ["Jonathan Doucette <jdoucette@physics.ubc.ca> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
